add file path for apikey
onedr0p/exportarr pull request #38
Opened 2021-11-09 03:00 UTC by phillipgreenii

**Description of the change**
Add optional file input for api key.

**Benefits**

It is more secure to read API key from file than pass via environment variable.

**Possible drawbacks**

None

**Applicable issues**

None

**Additional information**

None

2021-11-10 12:40 UTC, onedr0p commented
I am okay with this after reading in  urfave/cli docs:

> Note that default values set from file (e.g. FilePath) take precedence over default values set from the environment (e.g. EnvVar).

Thanks for the contribution!

2022-02-17 05:53 UTC, phillipgreenii commented
Whatever you think is best.

2022-03-30 01:29 UTC, onedr0p requested changes

2022-03-30 01:29 UTC, onedr0p commented on cmd/exportarr/main.go
> +			FilePath: fmt.Sprintf("/etc/exportarr/%s.apikey", arr),
```suggestion
			FilePath: "/etc/exportarr/apikey",
```

2022-03-30 01:29 UTC, onedr0p approved these changes

2022-03-30 01:29 UTC, merged